import { NextFunction, Request, Response } from 'express-serve-static-core';

export const monitors = (req: Request, res: Response, next: NextFunction) => {
  res.json({
    "monitors": [{
      "Monitor": {
        "Id": "5",
        "Name": "Monitor-5",
        "Notes": "\\u6e2c\\u8a66",
        "ServerId": "0",
        "StorageId": "0",
        "Type": "Ffmpeg",
        "Function": "Record",
        "Enabled": "1",
        "LinkedMonitors": null,
        "Triggers": "",
        "Device": "",
        "Channel": "0",
        "Format": "0",
        "V4LMultiBuffer": null,
        "V4LCapturesPerFrame": "1",
        "Protocol": null,
        "Method": "rtpRtsp",
        "Host": null,
        "Port": "",
        "SubPath": "",
        "Path": "rtsp:\/\/admin:admin@192.168.11.233:554",
        "Options": null,
        "User": null,
        "Pass": null,
        "Width": "1920",
        "Height": "1080",
        "Colours": "4",
        "Palette": "0",
        "Orientation": "ROTATE_0",
        "Deinterlacing": "0",
        "DecoderHWAccelName": null,
        "DecoderHWAccelDevice": null,
        "SaveJPEGs": "3",
        "VideoWriter": "2",
        "OutputCodec": null,
        "OutputContainer": null,
        "EncoderParameters": "# Lines beginning with # are a comment \r\n# For changing quality, use the crf option\r\n# 1 is best, 51 is worst quality\r\n#crf=23",
        "RecordAudio": "1",
        "RTSPDescribe": false,
        "Brightness": "-1",
        "Contrast": "-1",
        "Hue": "-1",
        "Colour": "-1",
        "EventPrefix": "Event-",
        "LabelFormat": "%N - %d\/%m\/%y %H:%M:%S",
        "LabelX": "0",
        "LabelY": "0",
        "LabelSize": "1",
        "ImageBufferCount": "20",
        "WarmupCount": "0",
        "PreEventCount": "5",
        "PostEventCount": "5",
        "StreamReplayBuffer": "0",
        "AlarmFrameCount": "1",
        "SectionLength": "600",
        "MinSectionLength": "10",
        "FrameSkip": "0",
        "MotionFrameSkip": "0",
        "AnalysisFPSLimit": null,
        "AnalysisUpdateDelay": "0",
        "MaxFPS": null,
        "AlarmMaxFPS": null,
        "FPSReportInterval": "100",
        "RefBlendPerc": "6",
        "AlarmRefBlendPerc": "6",
        "Controllable": "0",
        "ControlId": null,
        "ControlDevice": null,
        "ControlAddress": null,
        "AutoStopTimeout": null,
        "TrackMotion": "0",
        "TrackDelay": null,
        "ReturnLocation": "-1",
        "ReturnDelay": null,
        "DefaultRate": "100",
        "DefaultScale": "100",
        "DefaultCodec": "auto",
        "SignalCheckPoints": "0",
        "SignalCheckColour": "#0000BE",
        "WebColour": "#2a9d20",
        "Exif": false,
        "Sequence": "1",
        "TotalEvents": "13",
        "TotalEventDiskSpace": "23308664546",
        "HourEvents": "6",
        "HourEventDiskSpace": "9131395031",
        "DayEvents": "13",
        "DayEventDiskSpace": "23308664546",
        "WeekEvents": "13",
        "WeekEventDiskSpace": "23308664546",
        "MonthEvents": "13",
        "MonthEventDiskSpace": "23308664546",
        "ArchivedEvents": null,
        "ArchivedEventDiskSpace": null,
        "ZoneCount": "1",
        "Refresh": null
      },
      "Monitor_Status": {
        "MonitorId": "5",
        "Status": "Connected",
        "CaptureFPS": "6.67",
        "AnalysisFPS": "7.14",
        "CaptureBandwidth": "325318"
      }
    }]
  });
  next();
}
